import React from 'react'
import { Link } from 'react-router-dom'
import { ArrowUpRight, CalendarDays, CircleDollarSign, FileText, Users } from 'lucide-react'
import AdminLayout from '@/components/admin/AdminLayout'
import { dashboardData } from '@/data/dashboard'

const shortDate = (date) => new Intl.DateTimeFormat('en-SG', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(date))

export default function AdminDashboard() {
  const { stats, recentActivity, upcomingEvents } = dashboardData
  const overviewMetrics = [
    { label: 'Active members', value: stats.activeMembers, detail: `${stats.totalMembers} total members`, icon: Users, tone: 'teal' },
    { label: 'Pending applications', value: stats.pendingApplications, detail: 'Awaiting review', icon: FileText, tone: 'coral' },
    { label: 'Upcoming events', value: String(upcomingEvents.length).padStart(2, '0'), detail: 'Scheduled in the calendar', icon: CalendarDays, tone: 'cyan' },
    { label: 'Outstanding payments', value: `SGD ${stats.outstandingPayments.toLocaleString('en-SG')}`, detail: 'Open payment activity', icon: CircleDollarSign, tone: 'plum' },
  ]
  return <AdminLayout><div className="admin-dashboard">
    <section className="admin-dashboard-intro"><div><p className="admin-kicker"><span /> Admin portal </p><h1>WISTA Singapore<br /><em>at a glance.</em></h1><p className="admin-intro-copy">Monitor membership, applications, events and financial activity from one place.</p></div><p className="admin-update-note">Operational overview<br /><strong>Current workspace</strong></p></section>
    <section className="admin-overview" aria-labelledby="overview-heading"><div className="admin-section-heading"><p id="overview-heading">Operational overview</p><span>Live dashboard structure</span></div><div className="admin-metric-grid">{overviewMetrics.map(({ label, value, detail, icon: Icon, tone }) => <div key={label} className={`admin-metric admin-metric-${tone}`}><Icon size={17} aria-hidden="true" /><p>{label}</p><strong>{value}</strong><span>{detail}</span></div>)}</div></section>
    <section className="admin-membership-block" aria-labelledby="membership-heading"><div className="admin-section-heading"><p id="membership-heading">Membership overview</p><span>Current membership base</span></div><div className="admin-membership-data"><div><span>Active</span><strong>{stats.activeMembers}</strong></div><div><span>Pending</span><strong>{stats.pendingApplications}</strong></div><div><span>Expiring soon</span><strong>{stats.expiringMemberships}</strong></div><div><span>Outstanding</span><strong>SGD {stats.outstandingPayments.toLocaleString('en-SG')}</strong></div></div><div className="admin-inline-links"><Link to="/admin/members">View members <ArrowUpRight size={15} /></Link><Link to="/admin/applications">Review applications <ArrowUpRight size={15} /></Link></div></section>
    <div className="admin-dashboard-columns"><section className="admin-dashboard-panel admin-applications-panel" aria-labelledby="applications-heading"><div className="admin-panel-title"><div><p id="applications-heading">Applications</p><span>Current review queue</span></div><Link to="/admin/applications">View all <ArrowUpRight size={15} /></Link></div><div className="admin-queue-summary"><strong>{stats.pendingApplications}</strong><div><span>Applications pending review</span><p>Prioritise the application queue and continue EXCO review.</p></div></div><Link to="/admin/applications" className="admin-text-action">Review applications <ArrowUpRight size={15} /></Link></section><section className="admin-dashboard-panel admin-payment-panel" aria-labelledby="payments-heading"><div className="admin-panel-title"><div><p id="payments-heading">Payment activity</p><span>Finance overview</span></div><Link to="/admin/payments">Payments <ArrowUpRight size={15} /></Link></div><div className="admin-payment-total"><span>Outstanding payment activity</span><strong>SGD {stats.outstandingPayments.toLocaleString('en-SG')}</strong></div><p className="admin-panel-copy">Use the Payments module to review recorded transactions and invoice activity.</p></section></div>
    <div className="admin-dashboard-columns admin-dashboard-lower"><section className="admin-dashboard-panel admin-events-panel" aria-labelledby="events-heading"><div className="admin-panel-title"><div><p id="events-heading">Upcoming events</p><span>Programme calendar</span></div><Link to="/admin/events">View events <ArrowUpRight size={15} /></Link></div><div className="admin-event-list">{upcomingEvents.map((event) => <div key={event.id} className="admin-event-row"><time dateTime={event.date}><span>{new Date(event.date).toLocaleDateString('en-SG', { month: 'short' })}</span>{new Date(event.date).getDate()}</time><div><strong>{event.title}</strong><span>{shortDate(event.date)}</span></div><CalendarDays size={18} aria-hidden="true" /></div>)}</div></section><section className="admin-dashboard-panel admin-activity-panel" aria-labelledby="activity-heading"><div className="admin-panel-title"><div><p id="activity-heading">Recent activity</p><span>From the current dashboard feed</span></div></div><div className="admin-activity-list">{recentActivity.map((activity) => <div key={activity.id} className="admin-activity-row"><i aria-hidden="true" /><div><strong>{activity.action}</strong><span>{activity.user}{activity.event ? ` · ${activity.event}` : ''}</span></div><time>{activity.time}</time></div>)}</div></section></div>
    <section className="admin-quick-actions" aria-labelledby="quick-actions-heading"><div className="admin-section-heading"><p id="quick-actions-heading">Quick actions</p><span>Common workflows</span></div><div><Link to="/admin/applications">Review applications <ArrowUpRight size={15} /></Link><Link to="/admin/members">Manage members <ArrowUpRight size={15} /></Link><Link to="/admin/events">Manage events <ArrowUpRight size={15} /></Link><Link to="/admin/payments">Review payments <ArrowUpRight size={15} /></Link></div></section>
  </div></AdminLayout>
}
